version: "3.1"
services:
  sonet-telergam-bot:
    container_name: sonet-telegram-bot
    build:
      context: ./
      dockerfile: ./Dockerfile
    restart: always
    stdin_open: true
    tty: true
networks:
  sparow-core:
    external: false
