name: sonet-bot
services:
  sonet-bot:
    public: true
    build:
      context: .
      dockerfile: ./Dockerfile
    replicas: 2
    ports:
      - 80
    resources:
      cpu: 100m
      memory: 128Mi
    # volumes:
    #   - /data
