name: sonet-bot
services:
  sonet-bot:
    public: true
    build:
      context: .
      dockerfile: ./Dockerfile
    replicas: 1
    ports:
      - 80
    environment:
      - TELEGRAM_TOKEN=$TELEGRAM_TOKEN
    resources:
      cpu: 100m
      memory: 128Mi
    volumes:
      - ./data
